### ISSUE TITLE
Uncaught DOMException: Failed to execute 'disconnect' on 'AudioNode' error message thrown while running troubleshooter tests

### ISSUE THREAD

**Issue by srnarayanan** [webrtc/testrtc#224] opened 2016-12-22 18:28 UTC
**Browsers and versions affected**
M57 Canary 57.0.2959.0 in Mac

**Description**
Uncaught DOMException: Failed to execute 'disconnect' on 'AudioNode': the given destination is not connected.
Error thrown while running tests in https://test.webrtc.org/

**Steps to reproduce**
1. Open https://test.webrtc.org/
2. Click 'Start' to run tests

**Expected results**
All tests should pass without JS errors

**Actual results**
Uncaught DOMException: Failed to execute 'disconnect' on 'AudioNode': the given destination is not connected.
    at MicTest.onStopCollectingAudio (https://test.webrtc.org/main.js:10:15959)
    at e (https://test.webrtc.org/main.js:1:1111)
    at MicTest.g [as stopCollectingAudio] (https://test.webrtc.org/main.js:1:1163)
    at MicTest.collectAudio (https://test.webrtc.org/main.js:10:15846)
onStopCollectingAudio @ main.js:10
e @ main.js:1
g @ main.js:1
collectAudio @ main.js:10
main.js:10 Uncaught DOMException: Failed to execute 'disconnect' on 'AudioNode': the given destination is not connected.
    at MicTest.onStopCollectingAudio (https://test.webrtc.org/main.js:10:15959)
    at e (https://test.webrtc.org/main.js:1:1111)
    at MicTest.g [as stopCollectingAudio] (https://test.webrtc.org/main.js:1:1163)
    at MicTest.collectAudio (https://test.webrtc.org/main.js:10:15846)
onStopCollectingAudio @ main.js:10
e @ main.js:1
g @ main.js:1
collectAudio @ main.js:10
Error thrown while running tests

Screenshot attached

Please note that the Microphone and Camera tests pass (All green) without errors 

![screen shot 2016-12-22 at 10 27 54 am](https://cloud.githubusercontent.com/assets/14947786/21436004/5373426a-c831-11e6-9e32-20dc91321419.png)

CC: @KaptenJansson

**Comment by srnarayanan** [comment] 2016-12-22 18:48
The error goes away after I re-run the tests on page refresh

**Comment by cvranjani** [comment] 2016-12-28 18:04
This issue was occasionally observed on Chrome OS with M55 and M56. As srnarayanan@ mentioned, it does not reproduce consistently and the errors disappear after re-running the troubleshooter tests.

**Comment by KaptenJansson** [comment] 2016-12-29 08:04
Most likely a race condition most evident on slower devices. Need to check that the audioNode still exists before disconnecting it.

**Comment by KaptenJansson** [comment] 2018-03-08 14:29
Closing due to age and a new bug has been filed.

**Closed by KaptenJansson** 2018-03-08 14:29 UTC
