### ISSUE TITLE
Uncaught error thrown on minimizing window while screensharing using windows picker extension

### ISSUE THREAD

**Issue by srnarayanan** [webrtc/testrtc#166] opened 2015-12-09 22:30 UTC
Repro steps:
1. Browse to https://test.webrtc.org/manual/peer2peer/
2. Click screen capture and if you get an error, follow the instructions and install the extension.
3. Open the javascript console (alt+cmd+j or ctr+shift+j) and watch for any errors
4. Make sure to select a couple of different types of windows, e.g. 3rd party apps like skype or wordpad as well as OS windows like finder or Windows Explorer.
5. Select any one of the windows to share (ex: Finder window)
6. Observe that selected screen is shared/shown under 'Remote Video'
7. Now, Minimize the window that is shared

Expected results:
Minimizing a window while screensharing should not result in JS errors

Actual results:
JS console shows "Uncaught Error: [object MediaStream] MediaStreamTrack.onmute event has fired, no frames to the track."

Console logs and screenshot attached
[peer2peer screenshare console logs.txt](https://github.com/webrtc/testrtc/files/57424/peer2peer.screenshare.console.logs.txt)
![screenshot from screensharing page](https://cloud.githubusercontent.com/assets/14947786/11700891/65239dfa-9e81-11e5-810e-41677e951d1c.png)

**Comment by KaptenJansson** [comment] 2016-01-12 15:56
duplicate of #165

**Closed by KaptenJansson** 2016-01-12 15:56 UTC
Labels: bug
