### ISSUE TITLE
test.webrtc.org still fails to show the positive camera resolution results

### ISSUE THREAD

**Issue by selavazhagan** [webrtc/testrtc#158] opened 2015-11-19 21:27 UTC
Steps:
1. In the device Big with the build 48.0.2564.8/7647.2.0 dev, go to test.webrtc.org and click on 'Start'
2. Wait and check for the results

Expected results:
There should be no red marks seen for the Camera section

Actual results:
The camera resolution fails to show positive results for the 1280x720 resolution

There are no errors seen in the JS console logs

Also, the bug report from the device can be found below
[testrtc-2015-11-19T21-10-20.186Z.txt](https://github.com/webrtc/testrtc/files/39479/testrtc-2015-11-19T21-10-20.186Z.txt)
s run is attached here.

**Comment by selavazhagan** [comment] 2015-11-19 21:33
I am seeing the same kind of error in log as pointed out by Ted in the bug https://github.com/webrtc/testrtc/issues/149

**Comment by KaptenJansson** [comment] 2015-11-20 08:45
The device Big's camera does not support 1280x720, this can be seen if you click on the error to expand it, it will say "ConstraintsNotSatisfiedError" which means the constraints provided could not be fulfilled by getUserMedia, i.e. not supported. 

@tednakamura could you confirm that the camera on this device does not do HD?

**Comment by tednakamura** [comment] 2015-11-24 22:45
The dmesg on the device lists the webcam as:
```uvcvideo: Found UVC 1.00 device HD WebCam (04f2:b469)```

The only public documentation on the webcam's capabilities from Acer's site just say that it supports "HD," and indeed, the "HD" (1280x720) attempt in https://webrtc.github.io/samples/src/content/getusermedia/resolution/ works fine. However, the "Full HD" (1920x1280) attempt fails with this console output:
```
chrome: {"video":{"mandatory":{"minWidth":1920,"maxWidth":1920,"minHeight":1080,"maxHeight":1080}}}
NavigatorUserMediaError
constraintName: "minHeight"
message: ""
name: "ConstraintNotSatisfiedError"
```

So overall, I'm closing this as working as intended.

**Closed by tednakamura** 2015-11-24 22:45 UTC
